/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pparonson' at '2/12/16 4:55 PM' with Gradle 2.11
 *
 * @author pparonson, @date 2/12/16 4:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
